server:
 port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelmicro
    username: root
    password: 8207
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: USER_HOTEL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
eureka:
      instance:
        prefer-ip-address: true
      client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
          defaultZone: http://localhost:8761/eureka/
